plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = "${mod_version}"
group = "${maven_group}"
base.archivesName = "truenins"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

minecraft {
    mappings channel: 'official', version: "${minecraft_version}"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'truenins'
            mods {
                truenins {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'truenins'
            mods {
                truenins {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, 'truenins.refmap.json'
    config 'truenins.mixins.json'
}

repositories {
    maven { url = 'https://maven.aliyun.com/repository/central' }
    maven { url = 'https://maven.aliyun.com/repository/public' }
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://repo.spongepowered.org/maven/' }
    maven {
        url = uri("https://cursemaven.com")
    }

}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation(fg.deobf("curse.maven:Curios-API-309927:6418456"))
    implementation(fg.deobf("curse.maven:GeckoLib-388172:8285794"))
    implementation(fg.deobf("curse.maven:playerAnimator-658587:4587214"))
    implementation(fg.deobf("curse.maven:Iron's-Spells-'n-Spellbooks-855414:8680180"))
    implementation(fg.deobf("curse.maven:Iron's-Lib-1492763:8364892"))
}

jar {
    manifest {
        attributes([
            "Specification-Title"     : "truenins",
            "Specification-Vendor"    : "truenins",
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : project.jar.archiveVersion,
            "Implementation-Vendor"   : "truenins"
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
